import type { Metadata } from "next";
// import "@bnext/ui"
// import "../../../../packages/ui/src/styles/layout/layout.scss";
// import "../../../../packages/ui/src/styles/demo/Demos.scss";
import "primeicons/primeicons.css";
import "primeflex/primeflex.css";
import "@bnext/ui/dist/styles.css";
// import "../../../../packages/src/styles/lara-light-indigo/theme.css";

import { PrimeReactProvider } from "primereact/api";
import { LayoutProvider, ToastContextProvider } from "@bnext/context";

export const metadata: Metadata = {
  title: "Host App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const values = { ripple: true };

  return (
    <html lang="en">
      <body>
        <ToastContextProvider>
          <LayoutProvider>
            <PrimeReactProvider value={values}>
              {children}
            </PrimeReactProvider>
          </LayoutProvider>
        </ToastContextProvider>
      </body>
    </html>
  );
}
